=== nickt1995/WebAPI_0_NPT/movies.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified"
           targetNamespace="http://sample"
           xmlns="http://sample"
           elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="movies" type="rootType"/>
  
  <xs:complexType name="rootType">
    <xs:sequence>
      <xs:element name="movie" type="movieType" minOccurs="1" maxOccurs="unbounded"/>
      <xs:element name="actor" type="actorType" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="movieType">
    <xs:sequence>
      <xs:element name="title" type="xs:string"/>
      
      <xs:element name="year">
        <xs:simpleType>
          <xs:restriction base="xs:int">
            <xs:pattern value="[1-9]\d{3}"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>

      <xs:element name="genre">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="action"/>
            <xs:enumeration value="adventure"/>
            <xs:enumeration value="comedy"/>
            <xs:enumeration value="drama"/>
            <xs:enumeration value="fantasy"/>
            <xs:enumeration value="horror"/>
            <xs:enumeration value="mystery"/>
            <xs:enumeration value="thriller"/>
            <xs:enumeration value="western"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="actorType">
    <xs:sequence>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="dateOfBirth" type="xs:date"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== nickt1995/WebAPI_0_NPT/movies.xml
<?xml version="1.0"?>
<movies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://sample"
        xsi:schemaLocation="http://sample movies.xsd">
  <movie>
    <title>The Zarneki Intrusion</title>
    <year>1995</year>
    <genre>action</genre>
  </movie>
  <movie>
    <title>Weird Science 2: Weirder Science</title>
    <year>2019</year>
    <genre>comedy</genre>
  </movie>
  <actor>
    <name>Joe Shmoe</name>
    <dateOfBirth>1983-06-23</dateOfBirth>
  </actor>
  <actor>
    <name>Jane Doe</name>
    <dateOfBirth>1979-11-04</dateOfBirth>
  </actor>
</movies>
